<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Site.Master" AutoEventWireup="true" CodeBehind="Customer.aspx.cs" Inherits="Travel.Admin.Customer" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel runat="server" ID="pnGridView">
        <h1 style="text-align: center; margin-bottom: 30px;">Danh sách khách hàng</h1>

        <div class="text-right" style="margin-bottom: 40px;">
            <asp:Button runat="server" CssClass="btn btn-success" Text="Thêm khách hàng" ID="btnThem" OnClick="btnThem_Click" />
        </div>
        <asp:DataGrid ID="dgKH" runat="server"
            AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" Width="100%" CellPadding="5" OnPageIndexChanged="dgKH_PageIndexChanged"
            OnDeleteCommand="dgKH_DeleteCommand" OnEditCommand="dgKH_EditCommand"
            GridLines="None">
            <Columns>
                <asp:BoundColumn HeaderText="ID" DataField="ID"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="HoTen" DataField="HoTen"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="TenDangNhap" DataField="TenDangNhap"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="MatKhau" DataField="MatKhau"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="DiaChi" DataField="DiaChi"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="DienThoai" DataField="DienThoai"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="Email" DataField="Email"></asp:BoundColumn>
                <asp:BoundColumn HeaderText="NgayDangKy" DataField="NgayDangKy"></asp:BoundColumn>
                <asp:TemplateColumn HeaderText="Sửa">

                    <ItemTemplate>
                        <asp:LinkButton runat="server" CausesValidation="false" CommandName="Edit" Text="Sửa"></asp:LinkButton>
                    </ItemTemplate>
                </asp:TemplateColumn>
                <asp:TemplateColumn HeaderText="Xóa">
                    <ItemTemplate>
                        <asp:LinkButton runat="server" CausesValidation="false" OnClientClick="return confirm('Bạn muốn xóa bản ghi?');" CommandName="Delete" Text="Delete"></asp:LinkButton>
                    </ItemTemplate>
                </asp:TemplateColumn>
            </Columns>
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <SelectedItemStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" Mode="NumericPages" />
            <AlternatingItemStyle BackColor="White" />
            <ItemStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />

        </asp:DataGrid>
    </asp:Panel>
    <asp:Panel runat="server" ID="pnEditData" Visible="false">
        <h1>
            <asp:Label runat="server" ID="TieuDe" CssClass="text-center" EnableTheming="True" Font-Bold="True" Font-Strikeout="False" Font-Underline="True" Width="100%">Thêm mới khách hàng</asp:Label></h1>
        <div class="form-group">
            <label>ID</label>
            <asp:TextBox Enabled="false" runat="server" ID="ID" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Họ tên</label>
            <asp:TextBox runat="server" ID="HoTen" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Tên Đăng Nhập</label>
            <asp:TextBox runat="server" ID="TenDangNhap" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Mật khẩu</label>
            <asp:TextBox runat="server" ID="MatKhau" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Địa chỉ</label>
            <asp:TextBox runat="server" ID="DiaChi" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Điện thoại</label>
            <asp:TextBox runat="server" ID="DienThoai" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Email</label>
            <asp:TextBox runat="server" ID="Email" CssClass="form-control"></asp:TextBox>
        </div>
        <div class="form-group">
            <label>Ngày đăng ký</label>
            <asp:TextBox runat="server" ID="NgayDangKy" Enabled="false" CssClass="form-control"></asp:TextBox>
        </div>
        <asp:Button runat="server" ID="btnSubmit" CssClass="btn btn-success btn-lg" OnClick="btnSubmit_Click" Text="Thêm mới" />
        <asp:Button runat="server" ID="btnCancel" CssClass="btn btn-default btn-lg" OnClick="btnCancel_Click" Text="Hủy bỏ" />
    </asp:Panel>
</asp:Content>
